spring:
  application:
    name: the-crm-service
  profiles:
    active: local

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
        exclude: env
      path-mapping:
        health: '/api/health'
  server:
    base-path: /
    port: '8080'
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs