# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: the-crm-service-pipeline

on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml

    - name: Rename jar
      run: mv ${{ github.workspace }}/api/target/*.jar ${{ github.workspace }}/api/target/api.jar

    - name: Save jar
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/api/target/api.jar
        retention-days: 1

  docker_build_push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Download jar
      uses: actions/download-artifact@v3
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/build

    - name: Docker build
      run: |
        docker build . -t henriquelange/the-crm-service:${{ github.ref_name }}.dev

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker push
      run: |
        docker push henriquelange/the-crm-service:${{ github.ref_name }}.dev
